travis:
  secure:
    BINSTAR_TOKEN: JZ7jP3k4HbxnMjikC3JK+u8fsrQtiQ811Q7UD9c3uQqm+srj6B0gQO2CnE+IXEpYQTspXUrN6/UAm62is0g1pxwlQ7C4Kf7ja657qStk6rH34TFdf8+fiPpotDzG4MYEM8gkD84+6Q+LvV70h3Qftxg6QY77a2C5SBsR8qoFn0HnTJxfJrE1Zo6FB+CtNVqDQhITMjdn7o76m3ZfM/iRpUJhHNi6+w6ZOOHxn6kUJBGEO/brFNlspsfeBm9JXjrl/K1Odj0h6YM3hzo9AcPxoINYSGRlzwJzxCrYfbJiXe8lsMsFAV7Z8h3Lb6tW62LWm+bkhAm1eEM+rqEf88pnIrQc1fmJhXrwEFiKg1oqnXPzZ5GsS+HgVMlhu13EC47mcfOWRJBPIajI/MZNnJ9HpibEvk4icXVLjEbnWlYhXL9WbCavUDuWlRFR0G1SzKSJqhbRR4VDdLGalTbpambe+olQGnva3hnzc+TKvz+aDnc0YYKBuwk1RPcSPl0CxDHU4ygVyiLAefpGmUveJ434FkRVDS9+Z6MNO4oa/ctJgfV8LquaHLJhxxhDE2wROekdHB2ci4k4sg3Tn640KhZhXUUfepHbN7KrIXlQjh9DLRyNkkzW+24a+G3tt8AWsWlJTktfQQjCI6HITy7gGpE4e1d17/TleA85bbzYDnuLes4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
